### ISSUE TITLE
Pressing the delete key while editing tag list

### ISSUE THREAD

**Issue by streawkceur** [burtonator/polar-bookshelf#1358]
When I edit the tag list/add a tag for a document and press the delete key in the text field (as opposed to backspace), the warning regarding deleting a document opens. Version 1.80.10.

**Desktop (please complete the following information):**
Ubuntu

**Comment by burtonator** [comment]
I'll take a look but also note you're on a VERY old version and I think that's fixed now.  Could you test on 1.90.18 ?

Definitely upgrade!

**Comment by streawkceur** [comment]
I upgraded (now installed via snap, earlier install was via the Ubuntu
package), the problem persists but the repository was reset to default
:-( How can I get it back? The files of the old install still seem to
exist in ~/.polar.

2020-02-18 20:02 GMT+01:00, Kevin Burton <notifications@github.com>:

**Comment by streawkceur** [comment]
...fixed it by copying ~/.polar to snap/polar-bookshelf/85/.polar.

**Comment by burtonator** [comment]
should be n/a on 2.0
