### ISSUE TITLE
Keyboard shortcuts for scrolling lacking

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1447]
In 2.0 beta 13, I can no longer use the left and right arrow keys to scroll a PDF by a single page. In 1.0, this worked correctly.

This is distinct from scrolling with page up/page down, which scrolls by about a screenful (and thus ends up with the pages not aligned with the top of the screen). The right and left keys should move the top edge of the next or previous page to the top of the window, regardless of zoom level, as they do in 1.0.

Additionally, I cannot scroll or change 'pages' in an EPUB using the arrow keys.

**Comment by burtonator** [comment]
Thanks.  This should be an easy fix and I scheduled it for the 2.0.0 milestone.

**Comment by burtonator** [comment]
Fixed.

**Comment by sopoforic** [comment]
This is not entirely fixed.

In beta 16, I can now change pages in EPUBs with left/right, but still cannot scroll with up/down. Same with captured web pages.

Scrolling up and down in PDFs works as expected, but using left/right to change pages does not: it starts changing pages from the beginning of the document rather than the current position. So, if I've scrolled to thirty pages into the document and hit `right`, then I will be taken to the top of page 2. This is probably the same issue as #1444.
