### ISSUE TITLE
"Update Metadata" is unstable

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#1547]
2.0.61 on Windows 10

I've encountered a variety of problems with the "Update Metadata" feature. Was it perhaps not meant to be public, yet? Here are a few issues.

Attempting to set multiple items from the "Update Metadata" dialog results in only some being set. For example, the title only seems to update if no other changes are made.

I set an editor on a document, and now cannot edit that document's metadata again. Clicking "Update Metadata" from the context menu now crashes the document repo:

```
TypeError: e.values.map is not a function
    at StringArrayAutocompleteProperty.tsx:25
    at Object.useMemo (react-dom.production.min.js:165)
    at Object.<anonymous> (react.production.min.js:25)
    at StringArrayAutocompleteProperty.tsx:19
    at $o (react-dom.production.min.js:153)
    at gs (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:246)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
```

The editor I set on that doc does not show up as an automplete option on other docs.

There is a field for "Volume" but not "Number".

And, finally, none of the metadata seems to be used. It can't be displayed or searched for, AFAICT.

**Comment by burtonator** [comment]
This is fixed... and they're used in the most recent release :) the .map issue kind of snuck in so sorry about that

Volume is another issue though.. I think it needs to be a string because some volume names could be strings

**Comment by sopoforic** [comment]
Still happening in 2.0.75.

Also, the volume/number thing I meant was that I could not record e.g. "Blah Journal Vol. 5 No. 2".
