### ISSUE TITLE
Fails to properly capture Twitter conversation

### ISSUE THREAD

**Issue by stekern** [burtonator/polar-bookshelf#304]
OS: Ubuntu 18.04
Polar Bookshelf: 1.0.2 (latest .deb release)

**Reproduction steps:**
Capture the following Twitter conversation https://twitter.com/michael_nielsen/status/957763229454774272

**Current behavior:**
The webpage loads properly, but the formatting gets messed up when exporting it.

**Expected behavior:**
The exported file keeps the formatting of the loaded webpage.

**Comment by burtonator** [comment]
WOW.. you're right.  

You're seeing something like this?

![image](https://user-images.githubusercontent.com/45447/47234922-33a2f580-d38c-11e8-841e-914b52018e24.png)

**Comment by stekern** [comment]
Yes, exactly that.

**Comment by burtonator** [comment]
this still fails on the most recent builds, even with the vertical height fix. I think something is happening and we're not properly capturing the CSS or we're stripping an important part of the doc during capture.

**Comment by burtonator** [comment]
This is probably the bug.. we're probably stripping out something important during capture.

**Comment by burtonator** [comment]
really weird ... it seems that the twitter content is coming from the cache and there are no HTTP headers or tracing available to track this down.

**Comment by burtonator** [comment]
it seems to be loading a URL prefetchTimestamp... 

COMPLETELY purging the electron directory fixed this problem.

**Comment by burtonator** [comment]
The issue is related to removing scripts... not sure but the DOM isn't enough to keep the content stored locally? Maybe it's loading in an iframe?

**Comment by burtonator** [comment]
AHAH! I think this has to do with web components... I think the DOM is hidden within a web component div and we need ti rip it open for it to work.

**Comment by burtonator** [comment]
OK... I can get this problem to reproduce itself without polar.

I just copy the outer HTML after I've removed all the scripts ... then it won't load.

**Comment by burtonator** [comment]
OK.. It think the problem is because the page is creating its own stylesheets dynamically which is NOT reflected in the DOM. Then when we capture the page we are missing the stylesheet content.  

I already have code to fix this so I just need to implement it  properly.

**Comment by burtonator** [comment]
Fixed in 1.9.0

**Comment by stateless** [comment]
Still having this issue. Works on some tweets, but not the above example or the following:

WORKS:
https://twitter.com/stateless/status/1084550300499795969?s=09
https://twitter.com/devonzuegel/status/1086663374694477825

DOES NOT WORK:
https://mobile.twitter.com/JulieLMacArthur/status/1071198025689649153
https://twitter.com/adzebill/status/1085665589501128704?s=09

**Comment by burtonator** [comment]
Thanks.. actually this was a different bug but will be fixed in the next release.

Thx.
