### ISSUE TITLE
Archived document is suddenly blank (no text)

### ISSUE THREAD

**Issue by leliamesteban** [burtonator/polar-bookshelf#819]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Describe the bug**
I captured a [page](https://blog.cloudflare.com/1111-warp-better-vpn/), made some annotations, archived it and then when I went to look at it again, it's entirely white. I can see the highlights and annotations but no text. Also, I can't remember if it was this way originally but it's a lot longer than it should be. This happens sometimes (eg. [here](https://forum.artofmemory.com/t/gavinos-massive-memory-palace-system/28227/46)) and seems to be related to "endless" comments that just extend the page downwards. Sometimes these comments don't show up in the captured document and just end up as empty space.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by burtonator** [comment]
Could you test with the latest release? 1.17.2 ?  I think this is fixed.

**Comment by leliamesteban** [comment]
You mean just try to open the document again using the new version? That still doesn't work I'm afraid
