### ISSUE TITLE
Area highlight shown in the annotations bar is not the area highlighted in the document.

### ISSUE THREAD

**Issue by cjsmooth** [burtonator/polar-bookshelf#964]
**Describe the bug**
When creating an area highlight the area that appears in the annotation sidebar is an area slightly higher than the area that is actually highlighted in the document.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.19.2

**Example image**

![image](https://user-images.githubusercontent.com/50675221/57797241-e0d2c600-7741-11e9-913f-0ca5092ea2ee.png)

**Comment by burtonator** [comment]
Thanks.. can you try again on 1.19.4?  I think this bug is already fixed. If not please create a new ticket.

**Comment by cjsmooth** [comment]
It looks like it still exists in 1.19.4. I have created a new ticket.
